### ISSUE TITLE
batch insert error

### ISSUE THREAD

**Issue by cmdares** [crate/crate-jdbc#284] opened 2018-07-28 15:35 UTC
table1（id integer），use jdbc execute batch method to insert data，error！

**Comment by thucpk** [comment] 2018-12-14 17:55
Hi Crate Team,
It seems that jdbc don't support insert NULL value.
```SQL
CREATE TABLE IF NOT EXISTS log_test (
    "id" integer,"log_type" integer,"log_time" long, "server_name" string
)
INSERT INTO log_test ("id","log_type","log_time", "server_name") 
VALUES (NULL,NULL,NULL,NULL)

java.sql.BatchUpdateException: 
Batch entry 0 INSERT INTO log_test ("id","log_type","log_time", "server_name") 
VALUES (NULL,NULL,NULL,NULL) was aborted: 
ERROR: Can't map PGType with oid=26 to Crate type 
Call getNextException to see other errors in the batch.
```
It's okay if I use python driver or execute sql in server.

**Comment by seut** [comment] 2019-05-23 12:38
Sorry for the long delay, this somehow slipped through. We cannot reproduce this issue.
Following snippet works as expected:

```
    @Test
    public void testInsertNull() throws Exception {
        try (Connection conn = DriverManager.getConnection("...")) {
            Statement stmt1 = conn.createStatement();
            stmt1.execute("create table log_test (\n" +
                         "    \"id\" integer,\"log_type\" integer,\"log_time\" long, \"server_name\" string\n" +
                         ")");

            PreparedStatement stmt = conn.prepareStatement("insert into log_test (\"id\",\"log_type\",\"log_time\", \"server_name\") values (?, ?, ?, ?)");

            stmt.setNull(1, Types.INTEGER);
            stmt.setNull(2, Types.INTEGER);
            stmt.setNull(3, Types.BIGINT);
            stmt.setNull(4, Types.VARCHAR);
            stmt.addBatch();

            int[] results = stmt.executeBatch();
            assertArrayEquals(new int[]{1}, results);
        }
    }
```

I'm closing this now. If you still have this issue, please re-open with some reproducible steps including used CrateDB version.

**Closed by seut** 2019-05-23 12:38 UTC
Labels: needs feedback
